
name: flutter_examen
description: Proyecto base examen Flutter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.3
flutter:
  uses-material-design: true
